import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import ResponziveBar from "@/components/navbar";
import Footer from "@/components/footer";
import Credit from "@/components/credit";

const nimbus = localFont({
  src: "./nimbusreg.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className={cn(
          "min-h-screen bg-background antialiased tracking-wider",
          nimbus.className
        )}>
          <ResponziveBar />
          {children}
          <Footer />
          <Credit />
        </body>
      </ThemeProvider>
    </html>
  );
}
